let aircraft = Store.get('bellair.aircraft', window.DEFAULT_AIRCRAFT);
let airports = Store.get('bellair.airports', window.DEFAULT_AIRPORTS);
let quotes = Store.get('bellair.quotes', []);
let stops = [];
const $ = id => document.getElementById(id);
function fmt(n){return '$'+Math.round(n).toLocaleString('en-AU')}
function nm(a,b){const R=3440.065,rad=x=>x*Math.PI/180;const dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon);const x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function hoursToText(h){const m=Math.round(h*60);return `${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`}
function apFromInput(v){const code=(v.match(/\(([A-Z0-9]+)\)$/)||[])[1] || v.trim().toUpperCase(); return airports.find(a=>a.code.toUpperCase()===code) || airports.find(a=>`${a.name} ${a.code}`.toLowerCase().includes(v.toLowerCase()));}
function syncDatalist(){ $('airportList').innerHTML = airports.map(a=>`<option value="${a.name} (${a.code})"></option>`).join(''); }
function renderAircraftSelect(){ $('aircraftSelect').innerHTML = '<option value="">Select aircraft</option>'+aircraft.map(a=>`<option value="${a.id}">${a.name}</option>`).join(''); }
function renderMap(){const pts=[apFromInput($('depSearch').value), ...stops.map(s=>apFromInput(s.value)), apFromInput($('dstSearch').value)]; drawMap($('routeMap'), pts);}
function legFuelCheck(ac, legNm){ const hrs=legNm/ac.speed; const required=hrs*ac.fuelBurn + ac.fuelBurn*(ac.reserveMin/60); return {ok: required <= ac.usableFuel, required, maxNm: ((ac.usableFuel - ac.fuelBurn*(ac.reserveMin/60))/ac.fuelBurn)*ac.speed}; }
function calculate(){
  const ac=aircraft.find(a=>a.id===$('aircraftSelect').value); const dep=apFromInput($('depSearch').value); const dst=apFromInput($('dstSearch').value); const st=stops.map(s=>apFromInput(s.value)).filter(Boolean);
  if(!ac||!dep||!dst){alert('Select aircraft, departure and destination.'); return;}
  const pax=+$('paxInput').value||1; if(pax>ac.pax){ alert(`${ac.name} is set to max ${ac.pax} pax.`); return; }
  const route=[dep,...st,dst]; let dist=0,warnings=[];
  for(let i=0;i<route.length-1;i++){ const d=nm(route[i],route[i+1])*1.01; dist+=d; const fc=legFuelCheck(ac,d); if(!fc.ok) warnings.push(`${route[i].code} → ${route[i+1].code}: ${Math.round(d)} nm exceeds practical fuel range (~${Math.round(fc.maxNm)} nm). Add a fuel stop.`); }
  if($('returnFlight').checked) dist*=2;
  const time=dist/ac.speed; const landing=(+$('landingFee').value||0)*(route.length-1)*($('returnFlight').checked?2:1); const perPax=(+$('perPaxFee').value||0)*pax; const subtotal=time*ac.rate+landing+perPax; const margin=subtotal*((+$('margin').value||0)/100); const gst=(subtotal+margin)*0.1; const total=subtotal+margin+gst;
  $('quoteResult').classList.remove('hidden'); $('quoteRef').textContent='QUOTE '+Date.now().toString().slice(-6); $('quoteTotal').textContent=fmt(total); $('qRoute').textContent=route.map(a=>a.code).join(' → ')+($('returnFlight').checked?' → '+dep.code:''); $('qAircraft').textContent=ac.name; $('qPax').textContent=pax; $('qDistance').textContent=Math.round(dist)+' nm'; $('qTime').textContent=hoursToText(time); $('qGst').textContent=fmt(gst);
  $('fuelWarnings').innerHTML=warnings.map(w=>`<div class="fuel-warn bad">${w}</div>`).join('') || '<div class="fuel-warn">Fuel check passed for each planned leg using editable aircraft fuel data.</div>';
  $('routeSummary').textContent=`${$('qRoute').textContent} · ${Math.round(dist)} nm · ${hoursToText(time)}`; renderMap();
}
function addStop(value=''){ const wrap=document.createElement('div'); wrap.className='stop-row'; wrap.innerHTML=`<input list="airportList" placeholder="Stop / fuel airport" value="${value}"><button class="secondary">Remove</button>`; wrap.querySelector('button').onclick=()=>{wrap.remove();stops=stops.filter(x=>x!==wrap.querySelector('input'));renderMap();}; wrap.querySelector('input').oninput=renderMap; $('stops').appendChild(wrap); stops.push(wrap.querySelector('input')); }
function renderAirports(){ const q=($('airportFilter')?.value||'').toLowerCase(); $('airportRows').innerHTML=airports.filter(a=>`${a.code} ${a.name} ${a.state}`.toLowerCase().includes(q)).slice(0,80).map(a=>`<div class="row" onclick="editAirport('${a.code}')"><div class="row-title">${a.code} — ${a.name}</div><div class="row-meta">${a.state||''} · ${a.runway||'—'} m · ${a.surface||'—'} · ${a.fuel||'—'}</div></div>`).join(''); }
window.editAirport=function(code){ const a=airports.find(x=>x.code===code); if(!a)return; $('apCode').value=a.code;$('apName').value=a.name;$('apLat').value=a.lat;$('apLon').value=a.lon;$('apRunway').value=a.runway||'';$('apSurface').value=a.surface||'';$('apNotes').value=a.notes||''; document.querySelector('[data-tab="airports"]').click(); }
function saveAirport(){ const code=$('apCode').value.trim().toUpperCase(); if(!code) return; const item={code,name:$('apName').value.trim(),state:'',lat:+$('apLat').value,lon:+$('apLon').value,runway:+$('apRunway').value,surface:$('apSurface').value,fuel:'',notes:$('apNotes').value}; const i=airports.findIndex(a=>a.code===code); if(i>=0) airports[i]={...airports[i],...item}; else airports.push(item); Store.set('bellair.airports',airports); syncDatalist(); renderAirports(); alert('Airport saved.'); }
function renderAircraftEditor(){ $('aircraftEditor').innerHTML=aircraft.map(a=>`<div class="row air-edit"><div class="row-title">${a.name}</div><label>$/hr<input data-air="${a.id}" data-field="rate" type="number" value="${a.rate}"></label><label>kt<input data-air="${a.id}" data-field="speed" type="number" value="${a.speed}"></label><label>Pax<input data-air="${a.id}" data-field="pax" type="number" value="${a.pax}"></label><label>Fuel L<input data-air="${a.id}" data-field="usableFuel" type="number" value="${a.usableFuel}"></label></div>`).join(''); $('aircraftEditor').querySelectorAll('input').forEach(inp=>inp.onchange=()=>{const a=aircraft.find(x=>x.id===inp.dataset.air); a[inp.dataset.field]=+inp.value; Store.set('bellair.aircraft',aircraft); renderAircraftSelect();}); }
function saveQuote(){ const item={date:new Date().toLocaleString('en-AU'),route:$('qRoute').textContent,total:$('quoteTotal').textContent,aircraft:$('qAircraft').textContent}; quotes.unshift(item); Store.set('bellair.quotes',quotes); renderQuotes(); alert('Quote saved.'); }
function renderQuotes(){ $('savedQuotes').innerHTML=quotes.length?quotes.map(q=>`<div class="row"><div class="row-title">${q.total} · ${q.route}</div><div class="row-meta">${q.aircraft} · ${q.date}</div></div>`).join(''):'<p class="muted">No saved quotes yet.</p>'; }
function initTabs(){ document.querySelectorAll('.bottom-nav button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));$('tab-'+btn.dataset.tab).classList.add('active'); if(btn.dataset.tab==='airports')renderAirports(); if(btn.dataset.tab==='settings')renderAircraftEditor(); if(btn.dataset.tab==='quotes')renderQuotes();}); }
function init(){ renderAircraftSelect(); syncDatalist(); initTabs(); renderMap(); $('calcBtn').onclick=calculate; $('addStopBtn').onclick=()=>addStop(); $('depSearch').oninput=renderMap; $('dstSearch').oninput=renderMap; $('airportFilter').oninput=renderAirports; $('saveAirportBtn').onclick=saveAirport; $('saveQuoteBtn').onclick=saveQuote; $('resetAircraftBtn').onclick=()=>{if(confirm('Reset aircraft data?')){aircraft=window.DEFAULT_AIRCRAFT;Store.set('bellair.aircraft',aircraft);renderAircraftSelect();renderAircraftEditor();}}; }
init();
